#!/usr/bin/env python3

import rospy
from wrapper import rospyLogInfoWrapper, GlassSegmentationWrapper

if __name__ == '__main__':
    rospy.init_node('glass_semantic_node')
    rospyLogInfoWrapper('Node started')
    while not rospy.is_shutdown():
        segment = GlassSegmentationWrapper()
        rospy.spin()
    rospyLogInfoWrapper('Node stopped')