#!/usr/bin/env python3

import rospy
from wrapper import rospyLogInfoWrapper, SegmentationWrapper

if __name__ == '__main__':
    rospy.init_node('transformers_semantic_node')
    rospyLogInfoWrapper('Node started')
    while not rospy.is_shutdown():
        segment = SegmentationWrapper()
        rospy.spin()
    rospyLogInfoWrapper('Node stopped')